#!/bin/bash

if [[ $# -eq 1 ]]
then
	port=$1
else
	port=8080 
fi

echo "Starting Mash Calc on port ${port}"
exists=$(docker ps -a | grep mash-calc)

if [ -z "$exists" ]; then
	docker run -dit --name mash-calc -p "${port}":80 mash-calc
else
	docker start mash-calc
fi
